# Generated by Django 5.0.7 on 2024-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('text_area_name', models.CharField(max_length=100)),
                ('text_area_description', models.CharField(max_length=100)),
            ],
        ),
    ]
